import type { AppLocale } from './locale';

const en = {
  information: 'Information', artwork: 'Artwork', layout: 'Layout', motion: 'Motion', preview: 'Preview', builderSteps: 'Wedding invitation steps',
  informationKicker: 'Step 1', informationTitle: 'Wedding information', informationHelp: 'Add only the details that belong in this invitation. Optional fields may stay empty.', namesSection: 'Names / Couple', wordingSection: 'Wording', hostsSection: 'Families / Hosts', dateTimeSection: 'Date & Time', venueSection: 'Venue', rsvpSection: 'RSVP',
  step2: 'Step 2', chooseTemplate: 'Choose a template', templateHelp: 'The template controls visual design; layout and motion remain independent.', readyTemplate: 'ready template', preparingImage: 'Preparing image…', replaceBackground: 'Replace background', customBackground: 'Custom background', imageOnly: 'JPEG, PNG, or WebP · background image only', uploadBackground: 'Upload invitation background', removeBackground: 'Remove background and return to the ready template', uploadError: 'Could not prepare the image.', futureTemplates: 'Future custom templates enter the same registry without changing guest data or RSVP.',
  positionArtwork: 'Position artwork', positionHelp: 'Choose how the artwork sits on the invitation. Drag the preview when Fill is selected.', artworkDisplay: 'Artwork display', fit: 'Show whole artwork', fill: 'Fill invitation', fitHelp: 'The complete artwork stays visible. Position and Zoom are inactive.', fillHelp: 'The artwork fills the invitation. Drag the preview or use the controls below.', zoom: 'Zoom', dragArtwork: 'Drag to position artwork', positionFallback: 'Artwork position controls', moveUp: 'Move artwork up', moveDown: 'Move artwork down', moveLeft: 'Move artwork left', moveRight: 'Move artwork right', centerArtwork: 'Center artwork',
  fineTune: 'Fine tune', moreOptions: 'More options', safeZone: 'Text position', safeZoneHelp: 'Choose where invitation text sits over the artwork.', auto: 'Auto', top: 'Top', center: 'Center', bottom: 'Bottom',
  layoutKicker: 'Step 3', motionKicker: 'Step 4', layoutHelp: 'Choose one clear composition. Motion remains independent.', motionHelp: 'Choose how each existing scene enters. Layout remains unchanged.',
  overallContent: 'Overall content', overallContentHelp: 'Adjust the complete information composition without changing the artwork.', contentSize: 'Content size', horizontalPosition: 'Horizontal position', verticalPosition: 'Vertical position', resetContent: 'Reset content', resetEntireLayout: 'Reset entire layout', advancedBlockEditing: 'Advanced block editing', selectBlockHelp: 'Select a block here or directly in the preview, then adjust it as one unit.', blockSize: 'Block size', nudgeBlock: 'Nudge selected block', resetBlock: 'Reset block', occasion: 'Invitation', namesBlock: 'Names', detailsBlock: 'Date & time', rsvpBlock: 'Reception / RSVP',
  step3: 'Step 3', eventDetails: 'Event details', detailsHelp: 'The values below are the single source for invitation content.', invitationFormat: 'Invitation format', both: 'Bride and groom', women: 'Bride only', men: 'Groom only', family: 'Family', custom: 'Custom wording', opening: 'Opening wording', hosts: 'Hosts / family names', invitationWording: 'Invitation wording', groom: 'Groom name', bride: 'Bride name', familyNames: 'Family names', customArabic: 'Custom wording', day: 'Day', gregorian: 'Gregorian date', hijri: 'Hijri date', start: 'Start time', reception: 'Reception time', dinner: 'Dinner time', venue: 'Venue', city: 'City', map: 'Map URL', deadline: 'RSVP deadline',
  step4: 'Step 4', refinedStyle: 'A carefully tuned style', styleHelp: 'Colors, fonts, and decoration shape the visual identity without forcing layout or motion.', background: 'Background', headingColor: 'Heading color', imageOverlay: 'The image is the primary background; a neutral readability overlay is applied automatically.', flowers: 'Flower colors', namesFont: 'Names font', infoFont: 'Information font', music: 'Optional music URL', video: 'Optional background video URL',
  step5: 'Step 5', layoutMotion: 'Layout and motion', presentationHelp: 'Choose content placement and entrance independently from the template.', realPreview: 'True preview', previewTitle: 'What you see here is what the guest opens.', previewHelp: 'Play and replay scenes, open RSVP, and check name wrapping before sharing the link.',
} as const;
type Key = keyof typeof en;
const ar: Record<Key, string> = {
  information: 'المعلومات', artwork: 'العمل الفني', layout: 'التخطيط', motion: 'الحركة', preview: 'المعاينة', builderSteps: 'خطوات إنشاء دعوة الزفاف',
  informationKicker: 'الخطوة 1', informationTitle: 'معلومات الزفاف', informationHelp: 'أضيفي فقط التفاصيل المناسبة لهذه الدعوة. يمكن ترك الحقول الاختيارية فارغة.', namesSection: 'الأسماء / العروسان', wordingSection: 'الصياغة', hostsSection: 'العائلتان / الداعون', dateTimeSection: 'التاريخ والوقت', venueSection: 'المكان', rsvpSection: 'تأكيد الحضور',
  step2: 'الخطوة 2', chooseTemplate: 'اختاري القالب', templateHelp: 'القالب يحدد التصميم البصري؛ أما التخطيط والحركة فيُختاران بشكل مستقل.', readyTemplate: 'قالب جاهز', preparingImage: 'جارٍ تجهيز الصورة…', replaceBackground: 'استبدال الخلفية', customBackground: 'خلفية خاصة', imageOnly: 'JPEG أو PNG أو WebP · صورة خلفية فقط', uploadBackground: 'رفع صورة خلفية للدعوة', removeBackground: 'إزالة الخلفية والعودة للقالب الجاهز', uploadError: 'تعذر تجهيز الصورة.', futureTemplates: 'القوالب المخصصة المستقبلية تدخل السجل نفسه من دون تغيير بيانات الضيوف أو نظام الرد.',
  positionArtwork: 'ضبط العمل الفني', positionHelp: 'اختاري طريقة ظهور العمل الفني. اسحبي المعاينة عند اختيار ملء الدعوة.', artworkDisplay: 'عرض العمل الفني', fit: 'إظهار العمل كاملاً', fill: 'ملء الدعوة', fitHelp: 'يظهر العمل الفني كاملاً. الموضع والتكبير غير نشطين.', fillHelp: 'يملأ العمل الفني الدعوة. اسحبي المعاينة أو استخدمي عناصر التحكم.', zoom: 'التكبير', dragArtwork: 'اسحبي لضبط موضع العمل الفني', positionFallback: 'عناصر ضبط موضع العمل الفني', moveUp: 'تحريك العمل للأعلى', moveDown: 'تحريك العمل للأسفل', moveLeft: 'تحريك العمل لليسار', moveRight: 'تحريك العمل لليمين', centerArtwork: 'توسيط العمل',
  fineTune: 'ضبط إضافي', moreOptions: 'خيارات إضافية', safeZone: 'موضع النص', safeZoneHelp: 'اختاري مكان ظهور نص الدعوة فوق العمل الفني.', auto: 'تلقائي', top: 'أعلى', center: 'وسط', bottom: 'أسفل',
  layoutKicker: 'الخطوة 3', motionKicker: 'الخطوة 4', layoutHelp: 'اختاري تكويناً واضحاً. تبقى الحركة مستقلة.', motionHelp: 'اختاري طريقة دخول كل مشهد حالي. لا يتغير التخطيط.',
  overallContent: 'المحتوى بالكامل', overallContentHelp: 'اضبطي تكوين المعلومات بالكامل من دون تغيير العمل الفني.', contentSize: 'حجم المحتوى', horizontalPosition: 'الموضع الأفقي', verticalPosition: 'الموضع الرأسي', resetContent: 'إعادة ضبط المحتوى', resetEntireLayout: 'إعادة ضبط التخطيط بالكامل', advancedBlockEditing: 'تحرير متقدم للأقسام', selectBlockHelp: 'اختاري قسماً هنا أو مباشرة من المعاينة، ثم اضبطيه كوحدة واحدة.', blockSize: 'حجم القسم', nudgeBlock: 'تحريك القسم المحدد', resetBlock: 'إعادة ضبط القسم', occasion: 'عبارة الدعوة', namesBlock: 'الأسماء', detailsBlock: 'التاريخ والوقت', rsvpBlock: 'الاستقبال / تأكيد الحضور',
  step3: 'الخطوة 3', eventDetails: 'تفاصيل المناسبة', detailsHelp: 'النصوص أدناه هي المصدر الوحيد لمحتوى الدعوة.', invitationFormat: 'صيغة الدعوة', both: 'العروس والعريس', women: 'العروس فقط', men: 'العريس فقط', family: 'العائلة', custom: 'نص مخصص', opening: 'نص الافتتاح', hosts: 'أسماء الداعين / العائلتين', invitationWording: 'عبارة الدعوة', groom: 'اسم العريس', bride: 'اسم العروس', familyNames: 'أسماء العائلة', customArabic: 'النص المخصص', day: 'اليوم', gregorian: 'التاريخ الميلادي', hijri: 'التاريخ الهجري', start: 'وقت البداية', reception: 'وقت الاستقبال', dinner: 'وقت العشاء', venue: 'القاعة', city: 'المدينة', map: 'رابط الخريطة', deadline: 'موعد إغلاق الرد',
  step4: 'الخطوة 4', refinedStyle: 'نمط مضبوط بعناية', styleHelp: 'ألوان وخطوط وزخارف تضبط الهوية البصرية من دون فرض التكوين أو الحركة.', background: 'الخلفية', headingColor: 'لون العناوين', imageOverlay: 'الصورة هي الخلفية الأساسية، ويُطبّق عليها غطاء قراءة محايد تلقائياً.', flowers: 'ألوان الزهور', namesFont: 'خط الأسماء', infoFont: 'خط المعلومات', music: 'رابط موسيقى اختياري', video: 'رابط فيديو خلفية اختياري',
  step5: 'الخطوة 5', layoutMotion: 'التخطيط والحركة', presentationHelp: 'اختاري موضع المحتوى وطريقة دخوله بشكل مستقل عن تصميم القالب.', realPreview: 'المعاينة الحقيقية', previewTitle: 'كل ما تراه هنا هو ما يفتحه الضيف.', previewHelp: 'شغّل المشاهد وأعدها وافتح تأكيد الحضور وراجع التفاف الأسماء قبل إرسال الرابط.',
};
const translations = { ar, en } satisfies Record<AppLocale, Record<Key, string>>;
export const weddingBuilderT = (locale: AppLocale, key: Key) => translations[locale][key];
