import type { AppLocale } from './locale';

const en = {
  step2: 'Step 2', chooseTemplate: 'Choose a template', templateHelp: 'The template controls visual design; layout and motion remain independent.', readyTemplate: 'ready template', preparingImage: 'Preparing image…', replaceBackground: 'Replace background', customBackground: 'Custom background', imageOnly: 'JPEG, PNG, or WebP · background image only', uploadBackground: 'Upload invitation background', removeBackground: 'Remove background and return to the ready template', uploadError: 'Could not prepare the image.', futureTemplates: 'Future custom templates enter the same registry without changing guest data or RSVP.',
  step3: 'Step 3', eventDetails: 'Event details', detailsHelp: 'The values below are the single source for invitation content.', invitationFormat: 'Invitation format', both: 'Bride and groom', women: 'Bride only', men: 'Groom only', family: 'Family', custom: 'Custom wording', opening: 'Opening wording', hosts: 'Hosts / family names', invitationWording: 'Invitation wording', groom: 'Groom name', bride: 'Bride name', familyNames: 'Family names', customArabic: 'Custom wording', day: 'Day', gregorian: 'Gregorian date', hijri: 'Hijri date', start: 'Start time', reception: 'Reception time', dinner: 'Dinner time', venue: 'Venue', city: 'City', map: 'Map URL', deadline: 'RSVP deadline',
  step4: 'Step 4', refinedStyle: 'A carefully tuned style', styleHelp: 'Colors, fonts, and decoration shape the visual identity without forcing layout or motion.', background: 'Background', headingColor: 'Heading color', imageOverlay: 'The image is the primary background; a neutral readability overlay is applied automatically.', flowers: 'Flower colors', namesFont: 'Names font', infoFont: 'Information font', music: 'Optional music URL', video: 'Optional background video URL',
  step5: 'Step 5', layoutMotion: 'Layout and motion', presentationHelp: 'Choose content placement and entrance independently from the template.', layout: 'Layout', motion: 'Motion', realPreview: 'True preview', previewTitle: 'What you see here is what the guest opens.', previewHelp: 'Play and replay scenes, open RSVP, and check name wrapping before sharing the link.',
} as const;
type Key = keyof typeof en;
const ar: Record<Key, string> = {
  step2: 'الخطوة 2', chooseTemplate: 'اختاري القالب', templateHelp: 'القالب يحدد التصميم البصري؛ أما التخطيط والحركة فيُختاران بشكل مستقل.', readyTemplate: 'قالب جاهز', preparingImage: 'جارٍ تجهيز الصورة…', replaceBackground: 'استبدال الخلفية', customBackground: 'خلفية خاصة', imageOnly: 'JPEG أو PNG أو WebP · صورة خلفية فقط', uploadBackground: 'رفع صورة خلفية للدعوة', removeBackground: 'إزالة الخلفية والعودة للقالب الجاهز', uploadError: 'تعذر تجهيز الصورة.', futureTemplates: 'القوالب المخصصة المستقبلية تدخل السجل نفسه من دون تغيير بيانات الضيوف أو نظام الرد.',
  step3: 'الخطوة 3', eventDetails: 'تفاصيل المناسبة', detailsHelp: 'النصوص أدناه هي المصدر الوحيد لمحتوى الدعوة.', invitationFormat: 'صيغة الدعوة', both: 'العروس والعريس', women: 'العروس فقط', men: 'العريس فقط', family: 'العائلة', custom: 'نص مخصص', opening: 'نص الافتتاح', hosts: 'أسماء الداعين / العائلتين', invitationWording: 'عبارة الدعوة', groom: 'اسم العريس', bride: 'اسم العروس', familyNames: 'أسماء العائلة', customArabic: 'النص المخصص', day: 'اليوم', gregorian: 'التاريخ الميلادي', hijri: 'التاريخ الهجري', start: 'وقت البداية', reception: 'وقت الاستقبال', dinner: 'وقت العشاء', venue: 'القاعة', city: 'المدينة', map: 'رابط الخريطة', deadline: 'موعد إغلاق الرد',
  step4: 'الخطوة 4', refinedStyle: 'نمط مضبوط بعناية', styleHelp: 'ألوان وخطوط وزخارف تضبط الهوية البصرية من دون فرض التكوين أو الحركة.', background: 'الخلفية', headingColor: 'لون العناوين', imageOverlay: 'الصورة هي الخلفية الأساسية، ويُطبّق عليها غطاء قراءة محايد تلقائياً.', flowers: 'ألوان الزهور', namesFont: 'خط الأسماء', infoFont: 'خط المعلومات', music: 'رابط موسيقى اختياري', video: 'رابط فيديو خلفية اختياري',
  step5: 'الخطوة 5', layoutMotion: 'التخطيط والحركة', presentationHelp: 'اختاري موضع المحتوى وطريقة دخوله بشكل مستقل عن تصميم القالب.', layout: 'التخطيط', motion: 'الحركة', realPreview: 'المعاينة الحقيقية', previewTitle: 'كل ما تراه هنا هو ما يفتحه الضيف.', previewHelp: 'شغّل المشاهد وأعدها وافتح تأكيد الحضور وراجع التفاف الأسماء قبل إرسال الرابط.',
};
const translations = { ar, en } satisfies Record<AppLocale, Record<Key, string>>;
export const weddingBuilderT = (locale: AppLocale, key: Key) => translations[locale][key];
