import { ArrowRight, CalendarDays, Heart, History, LogOut, PartyPopper, Shield, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'wouter';

import type { CommercialSummary } from './commercial';
import { buildProjectRoute, type ProjectSummary } from './projects';
import { AppLanguageControl, useAppLocale } from '@/i18n/app-locale';

const entitlementKeys = { active: 'entitlementActive', suspended: 'entitlementSuspended', cancelled: 'entitlementCancelled', expired: 'entitlementExpired', none: 'notAvailable' } as const;
const lifecycleKeys = { planning: 'lifecyclePlanning', active: 'lifecycleActive', ended: 'lifecycleEnded', archived: 'lifecycleArchived', cancelled: 'lifecycleCancelled' } as const;

type DashboardAccount = { name: string; email: string; admin: boolean; eventCount: number; access: Partial<Record<ProjectSummary['type'], keyof typeof entitlementKeys>> };
type DashboardProject = ProjectSummary & { lifecycleStatus: keyof typeof lifecycleKeys };
type DashboardDraft = Pick<ProjectSummary, 'id' | 'type' | 'name'> & { updatedAt: string };
type Props = {
  projects: DashboardProject[]; drafts: DashboardDraft[]; account: DashboardAccount;
  commercial: Partial<Record<ProjectSummary['type'], CommercialSummary>>; product?: ProjectSummary['type'];
  onSignOut: () => void; onCreate: (type: ProjectSummary['type'], title: string) => Promise<void>;
  onRename: (id: string, title: string) => Promise<void>; onArchive: (id: string) => Promise<void>;
  onDelete: (id: string) => Promise<void>; onDeleteDraft: (id: string) => Promise<void>;
};

export function DashboardPage({ projects, drafts, account, commercial, product, onSignOut, onCreate, onRename, onArchive, onDelete, onDeleteDraft }: Props) {
  const { t, dir, locale } = useAppLocale();
  const [type, setType] = useState<ProjectSummary['type']>(product ?? 'wedding');
  const [title, setTitle] = useState('');
  const [names, setNames] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const shownProjects = product ? projects.filter((item) => item.type === product) : projects;
  const shownDrafts = product ? drafts.filter((item) => item.type === product) : drafts;
  const current = shownProjects.filter((item) => item.lifecycleStatus === 'planning' || item.lifecycleStatus === 'active');
  const history = shownProjects.filter((item) => item.lifecycleStatus !== 'planning' && item.lifecycleStatus !== 'active');
  const run = async (key: string, operation: Promise<void>) => { setBusy(key); setError(''); try { await operation; } catch { setError(t('operationFailed')); } finally { setBusy(''); } };
  const formatDate = (value?: string | null) => value ? new Date(value).toLocaleDateString(locale === 'ar' ? 'ar-SA' : 'en') : '—';

  const eventCards = (items: DashboardProject[], empty: string) => items.length === 0 ? <p className="mt-3 text-sm text-[#756F66]">{empty}</p> : <div className="mt-4 grid gap-4 md:grid-cols-2">{items.map((item) => {
    const Icon = item.type === 'wedding' ? Heart : PartyPopper;
    return <article key={`${item.type}-${item.id}`} className="rounded-3xl border border-[#D9D2C5] bg-white p-6 sm:p-8"><Link href={buildProjectRoute(item.type, item.id, 'overview')} className="focus-ring group block"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#0C2D24] text-[#D4B363]"><Icon size={20} /></span><ArrowRight className={`text-[#A4813C] transition group-hover:translate-x-1 ${dir === 'rtl' ? 'rotate-180' : ''}`} /></div><p className="mt-7 text-[10px] font-bold uppercase tracking-[.16em] text-[#8B7040]">{t(item.type)} · {t(lifecycleKeys[item.lifecycleStatus])}</p><h3 className="mt-2 break-words text-2xl font-semibold tracking-[-.035em]">{item.name}</h3><p className="mt-4 flex items-start gap-2 break-words text-xs text-[#756F66]"><CalendarDays className="mt-0.5 shrink-0" size={14} /><bdi>{formatDate(item.date)} · {item.venue || '—'}</bdi></p></Link><div className="mt-5 flex flex-wrap gap-2 border-t border-[#E8E2D8] pt-4"><input value={names[item.id] ?? item.name} onChange={(event) => setNames({ ...names, [item.id]: event.target.value })} className="min-h-11 min-w-0 flex-1 rounded-xl border border-[#D9D2C5] px-3 text-xs" aria-label={t('operationName')} /><button onClick={() => void run(item.id, onRename(item.id, names[item.id] ?? item.name))} className="min-h-11 rounded-full border px-3 text-xs">{t('rename')}</button>{(item.lifecycleStatus === 'planning' || item.lifecycleStatus === 'active') && <button onClick={() => void run(item.id, onArchive(item.id))} className="min-h-11 rounded-full border px-3 text-xs">{t('archive')}</button>}<button onClick={() => { if (window.confirm(t('confirmDelete'))) void run(item.id, onDelete(item.id)); }} className="min-h-11 rounded-full border px-3 text-xs text-[#8c302b]">{t('delete')}</button></div></article>;
  })}</div>;

  return <div className="min-h-[100dvh] bg-[#F5F2EC] text-[#17251F]">
    <header className="flex min-h-16 items-center justify-between border-b border-[#D9D2C5] bg-[#FAF8F4] px-5 sm:px-10"><Link href="/" className="text-xl font-semibold tracking-[-.04em]">Quick<span className="text-[#A4813C]">RSVP</span></Link><div className="flex items-center gap-2"><AppLanguageControl compact /><Link href="/account" className="focus-ring flex min-h-11 items-center gap-2 rounded-full border border-[#D9D2C5] px-4 text-xs font-semibold"><UserRound size={15} /><span className="hidden sm:inline">{t('account')}</span></Link>{account.admin && <Link href="/admin" className="focus-ring flex min-h-11 items-center gap-2 rounded-full border border-[#D9D2C5] px-4 text-xs font-semibold"><Shield size={15} />{t('admin')}</Link>}<button onClick={onSignOut} className="focus-ring flex min-h-11 items-center gap-2 rounded-full border border-[#D9D2C5] px-4 text-xs font-semibold"><LogOut size={15} /><span className="hidden sm:inline">{t('signOut')}</span></button></div></header>
    <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-16">
      <p className="text-xs font-bold uppercase tracking-[.16em] text-[#8B7040]">{product ? t(product === 'wedding' ? 'weddingPlanner' : 'partyPlanner') : t('overallDashboard')}</p><h1 className="mt-3 max-w-2xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">{t('manageEvents')}</h1>
      <nav className="mt-7 grid gap-3 sm:grid-cols-3" aria-label={t('projects')}><Link href="/" className="min-h-12 rounded-2xl border border-[#D9D2C5] bg-white px-5 py-4 text-sm font-semibold">{t('overallDashboard')}</Link><Link href="/planner/wedding" className="min-h-12 rounded-2xl border border-[#D9D2C5] bg-white px-5 py-4 text-sm font-semibold">{t('weddingPlanner')}</Link><Link href="/planner/party" className="min-h-12 rounded-2xl border border-[#D9D2C5] bg-white px-5 py-4 text-sm font-semibold">{t('partyPlanner')}</Link></nav>
      <section className="mt-5 rounded-3xl border border-[#D9D2C5] bg-white p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#0C2D24] text-[#D4B363]"><UserRound size={19} /></span><div className="min-w-0"><p className="text-xs font-semibold text-[#8B7040]">{t('backendConnected')}</p><p className="truncate font-semibold">{account.name}</p><p className="truncate text-xs text-[#756F66]" dir="ltr">{account.email}</p></div></div><div className="grid grid-cols-3 gap-2 text-center text-[10px]"><span className="rounded-xl bg-[#F5F2EC] px-3 py-2">{t('weddingAccess')}<b className="mt-1 block">{t(entitlementKeys[account.access.wedding ?? 'none'])}</b></span><span className="rounded-xl bg-[#F5F2EC] px-3 py-2">{t('partyAccess')}<b className="mt-1 block">{t(entitlementKeys[account.access.party ?? 'none'])}</b></span><span className="rounded-xl bg-[#F5F2EC] px-3 py-2">{t('eventShells')}<b className="mt-1 block">{account.eventCount}</b></span></div></div><p className="mt-5 border-t border-[#E8E2D8] pt-4 text-xs leading-5 text-[#756F66]">{t('localBuilderBoundary')}</p></section>
      <section className="mt-5 grid gap-4 md:grid-cols-2">{(['wedding', 'party'] as const).filter((item) => !product || product === item).map((item) => { const summary = commercial[item]; const productEvents = projects.filter((event) => event.type === item); const upcoming = productEvents.filter((event) => event.date && new Date(event.date).getTime() >= Date.now()).sort((a, b) => a.date.localeCompare(b.date))[0]; return <article key={item} className="rounded-3xl bg-[#0C2D24] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#D4B363]">{t(item === 'wedding' ? 'weddingPlanner' : 'partyPlanner')}</p><div className="mt-5 grid grid-cols-3 gap-2 text-xs"><span>{t('draftsCount')}<b className="mt-1 block text-lg">{drafts.filter((draft) => draft.type === item).length}</b></span><span>{t('publishedEvents')}<b className="mt-1 block text-lg">{productEvents.length}</b></span><span>{t('upcomingDate')}<b className="mt-1 block text-sm">{formatDate(upcoming?.date)}</b></span></div><div className="mt-5 grid grid-cols-3 gap-2 border-t border-white/15 pt-5 text-xs"><span>{t('allowance')}<b className="mt-1 block">{summary?.unlimited ? t('unlimited') : summary?.limit ?? '—'}</b></span><span>{t('consumed')}<b className="mt-1 block">{summary?.used ?? '—'}</b></span><span>{t('remaining')}<b className="mt-1 block">{summary?.unlimited ? t('unlimited') : summary?.remaining ?? '—'}</b></span></div>{summary?.used === null && <p className="mt-3 text-xs text-white/60">{t('usageUnavailable')}</p>}<Link href={`/planner/${item}`} className="mt-5 inline-flex min-h-11 items-center rounded-full border border-white/25 px-4 text-xs font-semibold">{t('openProject')}</Link></article>; })}</section>
      <section className={`mt-5 grid gap-3 rounded-3xl border border-[#D9D2C5] bg-white p-5 ${product ? 'sm:grid-cols-[minmax(0,1fr)_auto]' : 'sm:grid-cols-[150px_minmax(0,1fr)_auto]'}`}>{!product && <select value={type} onChange={(event) => setType(event.target.value as ProjectSummary['type'])} className="min-h-11 rounded-xl border border-[#D9D2C5] px-3"><option value="wedding">{t('wedding')}</option><option value="party">{t('party')}</option></select>}<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder={t((product ?? type) === 'wedding' ? 'newWedding' : 'newParty')} className="min-h-11 rounded-xl border border-[#D9D2C5] px-4" /><button disabled={!title.trim() || busy === 'create'} onClick={() => void run('create', onCreate(product ?? type, title.trim()).then(() => setTitle('')))} className="min-h-11 rounded-full bg-[#0C2D24] px-5 text-xs font-semibold text-white disabled:opacity-40">{t('startDraft')}</button></section>
      {error && <p className="mt-3 rounded-2xl bg-[#8c302b]/10 p-4 text-sm text-[#8c302b]" role="alert">{error}</p>}
      <section className="mt-10"><h2 className="text-2xl font-semibold">{t('designDrafts')}</h2><p className="mt-2 text-sm text-[#756F66]">{t('plannerWorkspace')}</p>{shownDrafts.length === 0 && <p className="mt-3 text-sm text-[#756F66]">{t('noDrafts')}</p>}<div className="mt-4 grid gap-4 md:grid-cols-2">{shownDrafts.map((draft) => { const Icon = draft.type === 'wedding' ? Heart : PartyPopper; return <article key={draft.id} className="rounded-3xl border border-[#D9D2C5] bg-white p-6"><Link href={`/drafts/${draft.type}/${encodeURIComponent(draft.id)}`} className="focus-ring block"><Icon className="text-[#A4813C]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.16em] text-[#8B7040]">{t(draft.type)} · {t('draft')}</p><h3 className="mt-2 text-xl font-semibold">{draft.name}</h3><p className="mt-3 text-xs text-[#756F66]">{formatDate(draft.updatedAt)}</p></Link><button onClick={() => { if (window.confirm(t('confirmDelete'))) void run(draft.id, onDeleteDraft(draft.id)); }} className="mt-4 min-h-11 rounded-full border px-4 text-xs text-[#8c302b]">{t('delete')}</button></article>; })}</div></section>
      <section className="mt-10"><h2 className="flex items-center gap-2 text-2xl font-semibold"><CalendarDays size={20} />{t('activeEvents')}</h2>{eventCards(current, t('noActiveEvents'))}</section>
      <section className="mt-10"><h2 className="flex items-center gap-2 text-2xl font-semibold"><History size={20} />{t('eventHistory')}</h2>{eventCards(history, t('noHistoricalEvents'))}</section>
    </main>
  </div>;
}
