import { useMemo, useState } from 'react';
import { BarChart3, CalendarDays, CreditCard, Headphones, LayoutTemplate, Shield, Users, type LucideIcon } from 'lucide-react';
import { Link } from 'wouter';

import { AppLanguageControl, useAppLocale } from '@/i18n/app-locale';
import { adminSections, buildAdminRoute, type AdminSection } from '@/app/projects';
import type { AdminSnapshot } from '@/backend/phase3';
import type { EntitlementStatus, ProductId } from '@/backend/types';

const icons: Record<AdminSection, LucideIcon> = { customers: Users, events: CalendarDays, templates: LayoutTemplate, usage: BarChart3, support: Headphones, subscriptions: CreditCard };
const statuses: EntitlementStatus[] = ['active', 'suspended', 'cancelled', 'expired'];
const entitlementLabel = { active: 'entitlementActive', suspended: 'entitlementSuspended', cancelled: 'entitlementCancelled', expired: 'entitlementExpired' } as const;
const lifecycleLabel = { planning: 'lifecyclePlanning', active: 'lifecycleActive', ended: 'lifecycleEnded', archived: 'lifecycleArchived', cancelled: 'lifecycleCancelled' } as const;
const activityLabel = { arrival_added: 'activityArrivalAdded', checkin_completed: 'activityCheckinCompleted', checkin_corrected: 'activityCheckinCorrected' } as const;
const purposeLabel = { private_source: 'privateSource', published_delivery: 'publishedDelivery' } as const;
const assetStatusLabel = { reserved: 'assetReserved', uploaded: 'assetUploaded', retired: 'assetRetired' } as const;

export function AdminPage({ section, snapshot, loading, error, onRefresh, onEntitlement, onTemplate }: { section: AdminSection; snapshot: AdminSnapshot; loading: boolean; error: string; onRefresh: () => Promise<void>; onEntitlement: (clientId: string, productId: ProductId, status: EntitlementStatus, endsAt: string | null) => Promise<void>; onTemplate: (id: string, active: boolean) => Promise<void> }) {
  const { t } = useAppLocale();
  return <div className="min-h-[100dvh] bg-[#F3F0E9] text-[#17251F] md:grid md:grid-cols-[240px_minmax(0,1fr)]">
    <aside className="hidden min-h-[100dvh] flex-col bg-[#0C2D24] p-5 text-white md:flex"><Link href="/" className="text-xl font-semibold">Quick<span className="text-[#D4B363]">RSVP</span></Link><p className="mt-2 text-[10px] font-bold uppercase tracking-[.16em] text-white/45">{t('superAdmin')} · {t('backendAuthoritative')}</p><nav className="mt-8 space-y-1" aria-label={t('superAdmin')}>{adminSections.map((item) => { const Icon = icons[item]; return <Link key={item} href={buildAdminRoute(item)} aria-current={section === item ? 'page' : undefined} className={`focus-ring flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm ${section === item ? 'bg-[#D4B363] text-[#10271F]' : 'text-white/65 hover:bg-white/[.06]'}`}><Icon size={16} />{t(item)}</Link>; })}</nav><div className="mt-auto space-y-2"><AppLanguageControl /><Link href="/" className="focus-ring flex min-h-11 items-center gap-2 rounded-xl px-3 text-sm text-white/60"><Shield size={16} />{t('projects')}</Link></div></aside>
    <div className="min-w-0"><header className="sticky top-0 z-30 border-b border-[#D9D2C5] bg-[#FAF8F4]/95 px-4 py-3 backdrop-blur md:px-8"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold md:hidden">Quick<span className="text-[#A4813C]">RSVP</span></p><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#8B7040]">{t('superAdmin')} · {t('backendAuthoritative')}</p></div><div className="flex items-center gap-2"><AppLanguageControl compact /><button onClick={() => void onRefresh()} className="min-h-11 rounded-full border border-[#D9D2C5] px-3 text-xs font-semibold">{t('refresh')}</button><Link href="/" className="focus-ring rounded-full border border-[#D9D2C5] px-3 py-2 text-xs font-semibold">{t('projects')}</Link></div></div><nav className="mt-3 flex gap-2 overflow-x-auto pb-1 md:hidden" aria-label={t('superAdmin')}>{adminSections.map((item) => <Link key={item} href={buildAdminRoute(item)} aria-current={section === item ? 'page' : undefined} className={`focus-ring shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${section === item ? 'bg-[#0C2D24] text-white' : 'border border-[#D9D2C5] bg-white'}`}>{t(item)}</Link>)}</nav></header>
      <main className="mx-auto max-w-[1440px] p-4 sm:p-7 md:p-10"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8B7040]">{t('platformOperations')}</p><h1 className="mt-2 break-words text-4xl font-semibold tracking-[-.05em] sm:text-5xl">{t(section)}</h1></div>{loading && <p className="mt-6 rounded-2xl bg-white p-4 text-sm">{t('loading')}</p>}{error && <p className="mt-6 rounded-2xl bg-[#8c302b]/10 p-4 text-sm text-[#8c302b]" role="alert">{error}</p>}<div className="mt-8">{section === 'customers' && <Customers snapshot={snapshot} />}{section === 'events' && <Events snapshot={snapshot} />}{section === 'templates' && <Templates snapshot={snapshot} onTemplate={onTemplate} />}{section === 'usage' && <Usage snapshot={snapshot} />}{section === 'support' && <Support snapshot={snapshot} />}{section === 'subscriptions' && <Subscriptions snapshot={snapshot} onSave={onEntitlement} />}</div></main>
    </div>
  </div>;
}

function Customers({ snapshot }: { snapshot: AdminSnapshot }) {
  const { t } = useAppLocale();
  const [query, setQuery] = useState('');
  const clients = snapshot.clients.filter((client) => `${client.display_name} ${client.id}`.toLowerCase().includes(query.toLowerCase()));
  return <div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('searchClients')} className="min-h-12 w-full rounded-xl border border-[#D9D2C5] bg-white px-4 sm:max-w-md" /><div className="mt-5 grid gap-3 lg:grid-cols-2">{clients.map((client) => { const entitlements = snapshot.entitlements.filter((item) => item.client_id === client.id); const events = snapshot.events.filter((event) => event.client_id === client.id); return <article key={client.id} className="rounded-3xl border border-[#D9D2C5] bg-white p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#8B7040]">{t('client')}</p><h2 className="mt-1 text-xl font-semibold">{client.display_name}</h2><p className="mt-1 break-all font-mono text-[10px] text-[#756F66]" dir="ltr">{client.id}</p></div><span className="rounded-full bg-[#F5F2EC] px-3 py-2 text-[10px] font-bold uppercase">{t(client.status === 'active' ? 'activeStatus' : 'suspendedStatus')}</span></div><div className="mt-5 grid grid-cols-2 gap-2"><Metric label={t('events')} value={events.length} /><Metric label={t('entitlements')} value={entitlements.length} /></div><div className="mt-4 flex flex-wrap gap-2">{entitlements.map((item) => <span key={item.id} className="rounded-full border border-[#D9D2C5] px-3 py-2 text-xs">{t(item.product_id)} · {t(entitlementLabel[item.status])}</span>)}</div></article>; })}</div></div>;
}

function Events({ snapshot }: { snapshot: AdminSnapshot }) {
  const { t } = useAppLocale();
  return <div className="grid gap-3">{snapshot.events.map((event) => { const guests = snapshot.guests.filter((guest) => guest.event_id === event.id); const confirmed = guests.reduce((sum, guest) => sum + guest.confirmed_party_size, 0); const checked = guests.reduce((sum, guest) => sum + guest.checked_in_count, 0); return <article key={event.id} className="rounded-2xl border border-[#D9D2C5] bg-white p-5"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_repeat(3,120px)] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#8B7040]">{t(event.product_id)} · {t(lifecycleLabel[event.lifecycle_status])}</p><h2 className="mt-1 font-semibold">{event.title}</h2><p className="mt-1 break-all font-mono text-[10px] text-[#756F66]" dir="ltr">{event.id}</p></div><Metric label={t('guestRecords')} value={guests.length} /><Metric label={t('confirmedHeadcount')} value={confirmed} /><Metric label={t('checkedInHeadcount')} value={checked} /></div><details className="mt-4 border-t border-[#E8E2D8] pt-4"><summary className="cursor-pointer text-xs font-bold text-[#8B7040]">{t('inspectGuests')}</summary><div className="mt-3 divide-y divide-[#E8E2D8]">{guests.map((guest) => <div key={guest.id} className="grid gap-1 py-3 text-sm sm:grid-cols-[minmax(0,1fr)_120px_120px]"><div><p className="font-semibold">{guest.name}</p>{guest.custom_message && <p className="mt-1 text-xs text-[#756F66]">{guest.custom_message}</p>}</div><span>{t(guest.rsvp_status)} · {guest.confirmed_party_size}</span><span>{t('checkedInHeadcount')} {guest.checked_in_count}</span></div>)}</div></details></article>; })}</div>;
}

function Templates({ snapshot, onTemplate }: { snapshot: AdminSnapshot; onTemplate: (id: string, active: boolean) => Promise<void> }) {
  const { t } = useAppLocale();
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{snapshot.templates.map((template) => <article key={template.id} className="rounded-2xl border border-[#D9D2C5] bg-white p-5"><LayoutTemplate className="text-[#A4813C]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.12em] text-[#8B7040]">{t(template.product_id)} · v{template.version}</p><h2 className="mt-1 font-semibold">{template.renderer_key}</h2><p className="mt-3 break-all font-mono text-[10px] text-[#756F66]" dir="ltr">{template.id}</p><button onClick={() => void onTemplate(template.id, !template.active)} className={`mt-5 min-h-11 w-full rounded-xl text-xs font-bold ${template.active ? 'border border-[#D9D2C5]' : 'bg-[#0C2D24] text-white'}`}>{template.active ? t('disableTemplate') : t('enableTemplate')}</button></article>)}</div>;
}

function Usage({ snapshot }: { snapshot: AdminSnapshot }) {
  const { t } = useAppLocale();
  const confirmed = snapshot.guests.reduce((sum, guest) => sum + guest.confirmed_party_size, 0);
  const checked = snapshot.guests.reduce((sum, guest) => sum + guest.checked_in_count, 0);
  const values = [[t('clients'), snapshot.clients.length], [t('events'), snapshot.events.length], [t('guestRecords'), snapshot.guests.length], [t('confirmedHeadcount'), confirmed], [t('checkedInHeadcount'), checked], [t('remainingExpected'), Math.max(confirmed - checked, 0)]] as const;
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{values.map(([label, value]) => <Metric key={label} label={label} value={value} />)}</div>;
}

function Support({ snapshot }: { snapshot: AdminSnapshot }) {
  const { t } = useAppLocale();
  return <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-3xl border border-[#D9D2C5] bg-white p-6"><Headphones className="text-[#A4813C]" /><h2 className="mt-5 text-xl font-semibold">{t('recentCheckinActivity')}</h2><div className="mt-4 divide-y divide-[#E8E2D8]">{snapshot.activity.slice(0, 20).map((item) => <div key={item.id} className="py-3 text-sm"><p className="font-semibold">{t(activityLabel[item.action as keyof typeof activityLabel])}</p><p className="mt-1 text-xs text-[#756F66]">{item.previous_count} → {item.new_count} · <bdi>{new Date(item.created_at).toLocaleString()}</bdi></p></div>)}</div></section><section className="rounded-3xl border border-[#D9D2C5] bg-white p-6"><LayoutTemplate className="text-[#A4813C]" /><h2 className="mt-5 text-xl font-semibold">{t('assetMetadata')}</h2><div className="mt-4 divide-y divide-[#E8E2D8]">{snapshot.assets.slice(0, 20).map((asset) => <div key={asset.id} className="py-3 text-sm"><p className="font-semibold">{t(purposeLabel[asset.purpose as keyof typeof purposeLabel])} · {t(assetStatusLabel[asset.status as keyof typeof assetStatusLabel])}</p><p className="mt-1 text-xs text-[#756F66]">{asset.content_type} · {Math.ceil(asset.byte_size / 1024)} KB</p></div>)}</div></section></div>;
}

function Subscriptions({ snapshot, onSave }: { snapshot: AdminSnapshot; onSave: (clientId: string, productId: ProductId, status: EntitlementStatus, endsAt: string | null) => Promise<void> }) {
  const { t } = useAppLocale();
  const [drafts, setDrafts] = useState<Record<string, { status: EntitlementStatus; ends: string }>>({});
  const [busy, setBusy] = useState('');
  const rows = useMemo(() => snapshot.clients.flatMap((client) => (['wedding', 'party'] as ProductId[]).map((product) => ({ client, product, entitlement: snapshot.entitlements.find((item) => item.client_id === client.id && item.product_id === product) }))), [snapshot]);
  return <div className="grid gap-3">{rows.map(({ client, product, entitlement }) => { const key = `${client.id}:${product}`; const draft = drafts[key] ?? { status: entitlement?.status ?? 'active', ends: entitlement?.ends_at?.slice(0, 10) ?? '' }; return <article key={key} className="rounded-2xl border border-[#D9D2C5] bg-white p-5"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_170px_170px_auto] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#8B7040]">{t(product)}</p><h2 className="font-semibold">{client.display_name}</h2></div><label className="text-xs text-[#756F66]">{t('status')}<select value={draft.status} onChange={(event) => setDrafts({ ...drafts, [key]: { ...draft, status: event.target.value as EntitlementStatus } })} className="mt-1 min-h-11 w-full rounded-xl border px-3 text-[#17251F]">{statuses.map((status) => <option key={status} value={status}>{t(entitlementLabel[status])}</option>)}</select></label><label className="text-xs text-[#756F66]">{t('expiry')}<input type="date" value={draft.ends} onChange={(event) => setDrafts({ ...drafts, [key]: { ...draft, ends: event.target.value } })} className="mt-1 min-h-11 w-full rounded-xl border px-3 text-[#17251F]" /></label><button disabled={busy === key} onClick={() => { setBusy(key); void onSave(client.id, product, draft.status, draft.ends ? new Date(`${draft.ends}T23:59:59`).toISOString() : null).finally(() => setBusy('')); }} className="min-h-11 rounded-xl bg-[#0C2D24] px-5 text-xs font-bold text-white disabled:opacity-40">{t('saveChanges')}</button></div></article>; })}</div>;
}

function Metric({ label, value }: { label: string; value: number }) {
  return <div className="rounded-2xl border border-[#D9D2C5] bg-white p-4"><p className="text-[10px] text-[#756F66]">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>;
}
